title: Verification Lab
description: Assertion-based verification lab for EECS151 (class project for CS294-189).
theme: just-the-docs

url: https://kanavmittal314.github.io/verification

# aux_links:
#   Template Repository: https://github.com/just-the-docs/just-the-docs-template
# aux_links: # remove if you don't want this link to appear on your pages
#   Template Repository: https://github.com/YOUR-USERNAME/YOUR-SITE-NAME
